# Codecov Configuration
# https://docs.codecov.com/docs/codecov-yaml

codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    # Overall project coverage
    project:
      default:
        target: auto
        threshold: 1%
        base: auto
        if_ci_failed: error

    # Coverage for changes in PR
    patch:
      default:
        target: 90%
        threshold: 5%
        base: auto
        if_ci_failed: error

comment:
  # Enable PR comments showing coverage
  require_changes: false
  require_base: false
  require_head: true

  # Comment layout
  layout: "header, diff, flags, components, footer"
  behavior: default

  # Show these sections in PR comments
  after_n_builds: 1

  # Hide complexity metrics (optional)
  hide_comment_details: false

ignore:
  - "tests/**/*"
  - "benchmark/**/*"
  - "docs/**/*"
  - "setup.py"
  - "**/__pycache__"
  - "**/*.pyc"
