[project]
name = "telepy"
version = "0.1.0"
description = "A Python diagnostic tool."
authors = [
    {name = "changlehung",email = "changlehung@gmail.com"}
]
license = {text = "Apache-2.0 license"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi (>=0.115.12,<0.116.0)"
]
[tool.poetry]
packages = [{ include = "telepy", from = "src" }]


[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"
