[project]
name = "telepy"
version = "0.1.0"
description = "A Python diagnostic tool."
authors = [{ name = "changlehung", email = "changlehung@gmail.com" }]
license = { text = "Apache-2.0" }
readme = "README.md"
requires-python = ">=3.11"
dependencies = ["fastapi>=0.115.12,<0.116.0"]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Programming Language :: Python :: 3.13",
    "Intended Audience :: Developers",
    "Operating System :: MacOS",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Topic :: Software Development :: Quality Assurance",
    "Topic :: Software Development :: Bug Tracking",
    "Topic :: System :: Logging",
]


[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

# code settings
[tool.ruff]
select = ["E", "F", "W", "I", "UP", "RUF"]
line-length = 120
target-version = "py313"
fix = false
